sudo: false
language: cpp
compiler:
- gcc
addons:
	apt:
		sources:
		- ubuntu-toolchain-r-test
		packages:
		- g++-6
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true" 
#matrix:
#	include:
#		- os:  linux
#			addons:
#				apt:
#					sources:
#						- ubuntu-toolchain-r-test
#					packages:
#						- g++6
#						- cmake
#			env:
#				- MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
#
#before_install:
#	- eval "${MATRIX_EVAL}"
#
script:
	- gcc -v && g++ -v && cmake --version
	- mkdir build
	- cd build
	- cmake .. && make
